### ISSUE TITLE
I can't double-click words in native mode, standard mode doesn't have the correct subtitle files

### ISSUE THREAD

**Issue by zlylupaf** [muzuiget/dualsub-supports#588]
If I use standard mode, the subtitle file doesn't exist.(If it did, I would be able to double-click to select it)
If I use native mode, The file exists but, I can't double-click to select it
The reason I need to double-click it: so I can translate it.
this is the video: https://www.youtube.com/watch?v=u6ztdG1A7rg

**Comment by muzuiget** [comment]
Standard mode speech recognition subtitles (with `+` suffix), using Dualsub's server for recognition, based on OpenAI Whisper, currently only supports recognition of English.

Your video is in Russian, so it will be displayed as `{ no-speech }` because no English sentences are recognized.

You can only use native mode for this kind of video, which uses subtitles provided by the YouTube server.

**Comment by muzuiget** [comment]
What's "double-clicking", you mean "text selection"?

![Screenshot_20240310_211725](https://github.com/muzuiget/dualsub-support/assets/330812/f2332220-9bc3-4998-bd04-874929a8aa92)

**Comment by muzuiget** [comment]
So all you need is to enable YouTube's native subtitles to select text, rather than the default behavior of dragging to move the position?

**Comment by muzuiget** [comment]
The default mouse behavior of YouTube's native subtitle renderer is to move the subtitle position.

Its HTML structure is not suitable for customization, and even implementing text selection is difficult.

Other extensions may already implement this function, and it is recommended to use other extensions.
